### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pepijn98** [KurozeroPB/ran-mitake#1]
- [x] Structure of the bot and commands
- [x] Implement basic music features
- [ ] Expand to more advanced music features
- [ ] Command for listen.moe
